type BusinessSettings {
	printBankAccounts: String
	productsDefaultSockControl: Boolean
	productsDefaultSalesWithoutStock: Boolean
	printDefaultFormat: String
	printHeader: String
	printNumberDecimals: Int
	printInvoicesA4Columns: [String]
	printInvoicesA5Columns: [String]
	sunatLegend2001: Boolean
	sunatLegend2002: Boolean
}

type Business {
	id: ID
	name: String
	ruc: Float
	fiscalAddress: String
	tradename: String
	ubigeo: String
	logo: String
	settings: BusinessSettings
}


input BusinessInput {
	name: String
	ruc: Float
	fiscalAddress: String
	tradename: String
	ubigeo: String
	logo: String
}

input RegisterBusinessInput {
	ruc: String
	solUsername: String
	solPassword: String
}

extend type Query {
	getBusinessByUser: [Business]!
}

extend type Mutation {
	createBusiness(input: RegisterBusinessInput!): Business!
	updateBusiness(id: String!, input: BusinessInput): Business!
}